export const collections = {
  PreparationOrCleaningMethod: [
    "Gas cutting",
    "Pickling",
    "Brushing",
    "Chemical cleaning",
    "Laser cutting",
    "Machining",
    "Plasma cutting",
    "Grinding",
    "Waterjet cutting",
  ],
  RootPassPreparationMethod: [
    "Brushing",
    "Chemical cleaning",
    "Shaping",
    "Machining",
    "Grinding",
  ],
  PassType: [
    "Root pass",
    "Fill pass",
    "Cover pass",
    "Sealing run",
    "Buffer pass",
  ],
  PolarityType: ["DC+", "DC-", "AC~"],
  DropletTransferType: [
    "Dip transfer",
    "Global transfer",
    "Spray transfer",
    "Pulsed arc",
    "Rotating arc",
    "Force arc",
    "Cold arc",
  ],
  WeldingPositions: [
    "PA",
    "PB",
    "PC",
    "PD",
    "PE",
    "PF",
    "PG",
    "PH",
    "H-L045",
    "H-L030",
    "H-L060",
    "PJ",
    "J-L045",
    "J-L030",
    "J-L060",
    "PK",
  ],
};
