export const DATA = {
  WPSNumber: "WPS001",
  Revision: "1",
  Caption: "Welding Procedure Specification",
  Designation: "Sample WPS",
  Location: "",
  WPQR: "WPQR001",
  WelderQualification: "131_P_BW_23_S_t5_PA_ss_nb",
  WeldingProcess: "131",
  SeamType: "P/Stumpfnaht",
  Customer: "MEYER WERFT GmbH",
  Manufacturer: "Merkle",
  PartNumber: "PartNr001",
  Drawing: "Drawing Nr 001",
  Examiner: "Gimecs",
  PreparationMethod: "Machining",
  RootPassPreparation: "Brushing",
  FirstParentMaterial: "3.1 EN 10225 S420G1+Q (1.8830)",
  SecondParentMaterial: "2.1 EN 10025-4 S420ML (1.8836)",
  ParentMaterialThickness: 5,
  OutsideDiameter: 8,
  PreheatTemperature: 10,
  IntermediatePassTemperature: 26,
  JointDesignImage: "",
  WeldBuildupImage: "",
  Remarks: "",
  Layers: [
    {
      Passes: {
        From: 1,
        To: 4,
      },
      Positions: "PA",
      PassType: "Root pass",
      Process: "131",
      Current: {
        firstValue: 110,
        secondValue: 120,
        mode: "Range",
        Parameters: [
          {
            Name: "Arc Length Correction",
            Value: "+10",
          },
          {
            Name: "Pulse Height Correction",
            Value: "+6",
          },
        ],
      },
      Voltage: {
        firstValue: 17,
        secondValue: 19,
        mode: "Range",
      },
      Polarity: "DC+",
      WireFeedSpeed: {
        firstValue: 6.5,
        secondValue: 7.5,
        mode: "Range",
      },
      TravelSpeed: {
        firstValue: 50,
        secondValue: 60,
        mode: "Range",
      },
      HeatInput: {
        firstValue: 1.5,
        secondValue: 2.19,
        mode: "Range",
      },
      FillerMetal: {
        Brandname: "MA-1070 (Al99,7)",
        Manufacturer: "MIGAL.CO",
        MaterialNumber: "3.0259",
        Description: "Rod/Wire electrode for Aluminum",
        Standard: "EN ISO 18273",
        StandardDesignation: "S Al 1070 (Al99,7)",
        Size: "0.8",
      },
      ShieldingGas: {
        Standard: "ISO 14175",
        Symbol: "M23",
        NominalComposition: "ArCO – 5/4",
        Brandname: "CORGON® 5S4",
        Manufacturer: "Linde",
        FlowRate: {
          firstValue: 15,
          secondValue: 18,
          mode: "Range",
        },
        PreflowTime: 5,
        PostflowTime: 10,
      },
      FurtherInformation: {
        TipToWorkDistance: {
          firstValue: 8,
          secondValue: 10,
          mode: "Range",
        },
        DropletTransfer: "Dip transfer",
        GasNozzleDiameter: {
          firstValue: 15,
          secondValue: 15,
          mode: "Range",
        },
        WeavingType: "Stringer Pass",
      },
    },
  ],
  CreatedBy: "Thomas Merkle",
  CreationDate: "2013-11-14",
  ApprovedBy: "Robert Lahnsteiner",
  ApprovalDate: "2013-11-14",
  ReleasedBy: "Oleksandr Gizelo",
  ReleaseDate: "2013-11-14",
};
