export const DATA = {
  WPSNumber: "WPS001",
  Revision: "1",
  Caption: "Welding Procedure Specification",
  Designation: "Sample WPS",
  Location: "",
  WPQR: "WPQR001",
  WelderQualification: "131_P_BW_23_S_t5_PA_ss_nb",
  WeldingProcess: "131",
  SeamType: "P/Stumpfnaht",
  Customer: "MEYER WERFT GmbH",
  Manufacturer: "Merkle",
  PartNumber: "PartNr001",
  Drawing: "Drawing Nr 001",
  Examiner: "Gimecs",
  PreparationMethod: "Machining",
  RootPassPreparation: "Brushing",
  FirstParentMaterial: "1.1 EN 10248-1 S240GP 1.0021",
  SecondParentMaterial: "1.1 EN 10248-1 S240GP 1.0021",
  ParentMaterialThickness: 5,
  OutsideDiameter: 8,
  PreheatTemperature: "RT",
  IntermediatePassTemperature: "RT",
  JointDesignImage: "",
  WeldBuildupImage: "",
  Remarks: "",
  Layers: [
    {
      Passes: {
        From: 1,
        To: 4,
      },
      Position: "PA",
      PassType: "Root pass",
      Process: "131",
      Current: {
        LowLimit: 110,
        HighLimit: 120,
        Parameters: [
          {
            Name: "ArcLengthCorrection",
            Value: "+10",
          },
          {
            Name: "PulseHeightCorrection",
            Value: "+6",
          },
        ],
      },
      Voltage: {
        LowLimit: 17,
        HighLimit: 19,
      },
      Polarity: "DC+",
      WireFeedSpeed: {
        LowLimit: 6.5,
        HighLimit: 7.5,
      },
      TravelSpeed: {
        LowLimit: 50,
        HighLimit: 60,
      },
      HeatInput: {
        LowLimit: 1.5,
        HighLimit: 2.19,
      },
      FillerMetal: {
        Brandname: "MA-1070 (Al99,7)",
        Manufacturer: "MIGAL.CO",
        MaterialNumber: "3.0259",
        Description: "Rod/Wire electrode for Aluminum",
        Standard: "EN ISO 18273",
        StandardDesignation: "S Al 1070 (Al99,7)",
        Size: "0.8",
      },
      ShieldingGas: {
        Designation: "ISO 14175 I1: ArCO - 5/4",
        Brandname: "Schweißargon spezial",
        Manufacturer: "Messer Group",
        FlowRate: {
          LowLimit: 15,
          HighLimit: 18,
        },
        PreflowTime: 5,
        PostflowTime: 10,
      },
      FurtherInformation: {
        Parameters: [
          {
            Name: "TipToWorkDistance",
            Value: "8 - 10",
          },
          {
            Name: "DropletTransfer",
            Value: "Dip transfer",
          },
          {
            Name: "GasNozzleDiameter",
            Value: "15",
          },
        ],
        WeavingType: "StringerPass",
      },
    },
  ],
  CreatedBy: "Thomas Merkle",
  CreationDate: "2013-11-14",
  ApprovedBy: "Robert Lahnsteiner",
  ApprovalDate: "2013-11-14",
  ReleasedBy: "Oleksandr Gizelo",
  ReleaseDate: "2013-11-14",
};
