export const fillers = [
  {
    Brandname: "MA-1070 (Al99,7)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.0259",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 1070 (Al99,7)",
    Size: "0.8",
  },
  {
    Brandname: "MA-1450 (Al99,5Ti)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.0805",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 1450 (Al99,5Ti)",
    Size: "0.8",
  },
  {
    Brandname: "MA-2319 (AlCu6MnZrTi)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 2319 (AlCu6MnZrTi)",
    Size: "0.8",
  },
  {
    Brandname: "MA-4018 (AlSi7Mg)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.2371",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 4018 (AlSi7Mg)",
    Size: "1.2",
  },
  {
    Brandname: "MA-4020 (AlSi3Mn)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 4020 (AlSi3Mn1)",
    Size: "0.8",
  },
  {
    Brandname: "MA-4043 (AlSi5)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.2245",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 4043A (AlSi5(A))",
    Size: "0.8",
  },
  {
    Brandname: "MA-4046 (AlSi10Mg)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.2382",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 4046 (AlSi10Mg)",
    Size: "1.2",
  },
  {
    Brandname: "MA-4047 (AlSi12)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.2585",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 4047A (AlSi12(A))",
    Size: "0.8",
  },
  {
    Brandname: "MA-5087 (AlMg4,5MnZr)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3546",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 5087 (AlMg4,5MnZr(A))",
    Size: "0.8",
  },
  {
    Brandname: "MA-5183 (AlMg4,5Mn0,7)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3548",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 5183 (AlMg4,5Mn0,7(A))",
    Size: "0.8",
  },
  {
    Brandname: "MA-5356 (AlMg5Cr)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3556",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 5356 (AlMg5Cr(A))",
    Size: "0.8",
  },
  {
    Brandname: "MA-5554 (AlMg2,7Mn)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3538",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 5554 (AlMg2,7Mn)",
    Size: "0.8",
  },
  {
    Brandname: "MA-5556 (AlMg5Mn)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 5556A (AlMg5Mn1(A))",
    Size: "0.8",
  },
  {
    Brandname: "MA-5754 (AlMg3)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3536",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "EN ISO 18273",
    StandardDesignation: "S Al 5754 (AlMg3)",
    Size: "0.8",
  },
  {
    Brandname: "MA-6063 (AlMg0,7SiTiB)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "",
    Description: "Rod/Wire electrode for Aluminum",
    Standard: "",
    StandardDesignation: "",
    Size: "0.8",
  },
  {
    Brandname: "ML CuAl8",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0921",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 6100 (CuAl7)",
    Size: "0.8",
  },
  {
    Brandname: "ML CuAl8Ni2",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0922",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 6327 (CuAl8Ni2Fe2Mn2)",
    Size: "1.0",
  },
  {
    Brandname: "ML CuAl8Ni6",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0923",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 6328 (CuAl9Ni5Fe3Mn2)",
    Size: "1.0",
  },
  {
    Brandname: "ML CuAl9Fe",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0937",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 6180 (CuAl10Fe1)",
    Size: "0.8",
  },
  {
    Brandname: "ML CuMn13Al7",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1367",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 6338 (CuMn13Al8Fe3Ni2)",
    Size: "0.8",
  },
  {
    Brandname: "ML CuNi10Fe",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0873",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 7061 (CuNi10)",
    Size: "1.0",
  },
  {
    Brandname: "ML CuNi30Fe",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0837",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 7158 (CuNi30Mn1FeTi)",
    Size: "1.0",
  },
  {
    Brandname: "ML CuSi28L",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1461",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 6560 (CuSi3Mn1)",
    Size: "0.8",
  },
  {
    Brandname: "ML CuSi3",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1461",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 6560 (CuSi3Mn1)",
    Size: "0.8",
  },
  {
    Brandname: "ML CuSn",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1006",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 1898A (CuSn1MnSi)",
    Size: "0.8",
  },
  {
    Brandname: "ML CuSn6",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1022",
    Description: "Rod/Wire electrode for Copper",
    Standard: "ISO 24373",
    StandardDesignation: "S Cu 5180A (CuSn6P)",
    Size: "0.8",
  },
  {
    Brandname: "ML 19.9 LSi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4316",
    Description: "Stainless steel welding wires/rods",
    Standard: "DIN EN ISO 14343-A/G",
    StandardDesignation: "19 9 L Si",
    Size: "0.8",
  },
  {
    Brandname: "ML 23.12 LSi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4332",
    Description: "Stainless steel welding wires/rods",
    Standard: "DIN EN ISO 14343-A/G",
    StandardDesignation: "23 12 L Si",
    Size: "0.8",
  },
  {
    Brandname: "ML 29.9",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4337",
    Description: "Stainless steel welding wires/rods",
    Standard: "DIN EN ISO 14343-A/G",
    StandardDesignation: "29.9",
    Size: "0.8",
  },
  {
    Brandname: "ML 18.8 Mn",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4370",
    Description: "Stainless steel welding wires/rods",
    Standard: "DIN EN ISO 14343-A/G",
    StandardDesignation: "18 8 Mn",
    Size: "0.8",
  },
  {
    Brandname: "ML 19.12.3 LSi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4430",
    Description: "Stainless steel welding wires/rods",
    Standard: "DIN EN ISO 14343-A/G",
    StandardDesignation: "19 12 3 Lsi",
    Size: "0.8",
  },
  {
    Brandname: "ML 22.9.3 NL",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4462",
    Description: "Stainless steel welding wires/rods",
    Standard: "DIN EN ISO 14343-A/G",
    StandardDesignation: "22 9 3 N L",
    Size: "0.8",
  },
  {
    Brandname: "ML 19.12.3 NbSi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4576",
    Description: "Stainless steel welding wires/rods",
    Standard: "DIN EN ISO 14343-A/G",
    StandardDesignation: "19 12 3 NbSi",
    Size: "0.8",
  },
  {
    Brandname: "ML 25.20",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4842",
    Description: "Stainless steel welding wires/rods",
    Standard: "DIN EN ISO 14343-A/G",
    StandardDesignation: "25.20",
    Size: "0.8",
  },
  {
    Brandname: "NiCr20Nb",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.4806",
    Description: "Welding wires/rods for Nickel alloys",
    Standard: "EN ISO 18274",
    StandardDesignation: "S Ni 6082 (NiCr20Mn3Nb)",
    Size: "1.0",
  },
  {
    Brandname: "NiCr21Mo9Nb",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.4831",
    Description: "Welding wires/rods for Nickel alloys",
    Standard: "EN ISO 18274",
    StandardDesignation: "S Ni 6625 (NiCr22Mo9Nb)",
    Size: "1.0",
  },
  {
    Brandname: "NiCu30MnTi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.4377",
    Description: "Welding wires/rods for Nickel alloys",
    Standard: "EN ISO 18274",
    StandardDesignation: "S Ni 4060 (NiCu30Mn3Ti)",
    Size: "1.0",
  },
  {
    Brandname: "NiFe2",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "",
    Description: "Welding wires/rods for Nickel alloys",
    Standard: "DIN 8573",
    StandardDesignation: "SG - NiFe2",
    Size: "1.0",
  },
  {
    Brandname: "NiTi4",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.4155",
    Description: "Welding wires/rods for Nickel alloys",
    Standard: "EN ISO 18274",
    StandardDesignation: "S Ni 2061 (NiTi3)",
    Size: "1.0",
  },
];
