export const fillers = [
  {
    CommertialDesignation: "MA-1070 (Al99,7)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.0259",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 1070 (Al99,7)",
  },
  {
    CommertialDesignation: "MA-1450 (Al99,5Ti)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.0805",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 1450 (Al99,5Ti)",
  },
  {
    CommertialDesignation: "MA-2319 (AlCu6MnZrTi)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 2319 (AlCu6MnZrTi)",
  },
  {
    CommertialDesignation: "MA-4018 (AlSi7Mg)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.2371",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4018 (AlSi7Mg)",
  },
  {
    CommertialDesignation: "MA-4020 (AlSi3Mn)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4020 (AlSi3Mn1)",
  },
  {
    CommertialDesignation: "MA-4043 (AlSi5)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.2245",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4043A (AlSi5(A))",
  },
  {
    CommertialDesignation: "MA-4046 (AlSi10Mg)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.2382",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4046 (AlSi10Mg)",
  },
  {
    CommertialDesignation: "MA-4047 (AlSi12)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.2585",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4047A (AlSi12(A))",
  },
  {
    CommertialDesignation: "MA-5087 (AlMg4,5MnZr)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3546",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5087 (AlMg4,5MnZr(A))",
  },
  {
    CommertialDesignation: "MA-5183 (AlMg4,5Mn0,7)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3548",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5183 (AlMg4,5Mn0,7(A))",
  },
  {
    CommertialDesignation: "MA-5356 (AlMg5Cr)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3556",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5356 (AlMg5Cr(A))",
  },
  {
    CommertialDesignation: "MA-5554 (AlMg2,7Mn)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3538",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5554 (AlMg2,7Mn)",
  },
  {
    CommertialDesignation: "MA-5556 (AlMg5Mn)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5556A (AlMg5Mn1(A))",
  },
  {
    CommertialDesignation: "MA-5754 (AlMg3)",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "3.3536",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5754 (AlMg3)",
  },
  {
    CommertialDesignation: "MA-6063 (AlMg0,7SiTiB)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "",
  },
  {
    CommertialDesignation: "ML CuAl8",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0921",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6100 (CuAl7)",
  },
  {
    CommertialDesignation: "ML CuAl8Ni2",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0922",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6327 (CuAl8Ni2Fe2Mn2)",
  },
  {
    CommertialDesignation: "ML CuAl8Ni6",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0923",
    Description: "Rod/Wire electrode for Copper",
    Designation: "DIN 1733: SG-CuAl8Ni6",
  },
  {
    CommertialDesignation: "ML CuAl9Fe",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0937",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6180 (CuAl10Fe1)",
  },
  {
    CommertialDesignation: "ML CuMn13Al7",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1367",
    Description: "Rod/Wire electrode for Copper",
    Designation: "DIN 1733: SG-CuMn13Al7",
  },
  {
    CommertialDesignation: "ML CuNi10Fe",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0873",
    Description: "Rod/Wire electrode for Copper",
    Designation: "IDIN 1733: SG-CuNi10Fe",
  },
  {
    CommertialDesignation: "ML CuNi30Fe",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.0837",
    Description: "Rod/Wire electrode for Copper",
    Designation: "IDIN 1733: SG-CuNi30Fe",
  },
  {
    CommertialDesignation: "ML CuSi28L",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1461",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6560 (CuSi3Mn1)",
  },
  {
    CommertialDesignation: "ML CuSi3",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1461",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6560 (CuSi3Mn1)",
  },
  {
    CommertialDesignation: "ML CuSn",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1006",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 1898A (CuSn1MnSi)",
  },
  {
    CommertialDesignation: "ML CuSn6",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.1022",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 5180A (CuSn6P)",
  },
  {
    CommertialDesignation: "ML 19.9 LSi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4316",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 19 9 L Si",
  },
  {
    CommertialDesignation: "ML 23.12 LSi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4332",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 23 12 L Si",
  },
  {
    CommertialDesignation: "ML 29.9",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4337",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 29.9",
  },
  {
    CommertialDesignation: "ML 18.8 Mn",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4370",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 18 8 Mn",
  },
  {
    CommertialDesignation: "ML 19.12.3 LSi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4430",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 19 12 3 Lsi",
  },
  {
    CommertialDesignation: "ML 22.9.3 NL",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4462",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 22 9 3 N L",
  },
  {
    CommertialDesignation: "ML 19.12.3 NbSi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4576",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 19 12 3 NbSi",
  },
  {
    CommertialDesignation: "ML 25.20",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "1.4842",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 25.20",
  },
  {
    CommertialDesignation: "NiCr20Nb",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.4806",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "EN ISO 18274: S Ni 6082 (NiCr20Mn3Nb)",
  },
  {
    CommertialDesignation: "NiCr21Mo9Nb",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.4831",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "EN ISO 18274: S Ni 6625 (NiCr22Mo9Nb)",
  },
  {
    CommertialDesignation: "NiCu30MnTi",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.4377",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "EN ISO 18274: S Ni 4060 (NiCu30Mn3Ti)",
  },
  {
    CommertialDesignation: "NiFe2",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "DIN 8573: SG - NiFe2",
  },
  {
    CommertialDesignation: "NiTi4",
    Manufacturer: "MIGAL.CO",
    MaterialNumber: "2.4155",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "DIN 1736: SG - NiTi4",
  },
];
