export const fillers = [
  {
    Brandname: "MA-1070 (Al99,7)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 1070 (Al99,7) 3.0259",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-1450 (Al99,5Ti)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 1450 (Al99,5Ti) 3.0805",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-2319 (AlCu6MnZrTi)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 2319 (AlCu6MnZrTi)",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-4018 (AlSi7Mg)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4018 (AlSi7Mg) 3.2371",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-4020 (AlSi3Mn)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4020 (AlSi3Mn1)",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-4043 (AlSi5)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4043A (AlSi5(A)) 3.2245",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-4046 (AlSi10Mg)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4046 (AlSi10Mg) 3.2382",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-4047 (AlSi12)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 4047A (AlSi12(A)) 3.2585",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-5087 (AlMg4,5MnZr)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5087 (AlMg4,5MnZr(A)) 3.3546",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-5183 (AlMg4,5Mn0,7)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5183 (AlMg4,5Mn0,7(A)) 3.3548",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-5356 (AlMg5Cr)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5356 (AlMg5Cr(A)) 3.3556",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-5554 (AlMg2,7Mn)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5554 (AlMg2,7Mn) 3.3538",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-5556 (AlMg5Mn)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5556A (AlMg5Mn1(A))",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-5754 (AlMg3)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 5754 (AlMg3) 3.3536",
    Diameter: 1.2,
  },
  {
    Brandname: "MA-6063 (AlMg0,7SiTiB)",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Aluminium",
    Designation: "EN ISO 18273: S Al 6063 (AlMg0,7SiTiB) 3.3537",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuAl8",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6100 (CuAl7) 2.0921",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuAl8Ni2",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6327 (CuAl8Ni2Fe2Mn2) 2.0922",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuAl8Ni6",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "DIN 1733: SG-CuAl8Ni6 2.0923",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuAl9Fe",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6180 (CuAl10Fe1) 2.0937",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuMn13Al7",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "DIN 1733: SG-CuMn13Al7 2.1367",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuNi10Fe",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "IDIN 1733: SG-CuNi10Fe 2.0873",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuNi30Fe",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "IDIN 1733: SG-CuNi30Fe 2.0837",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuSi28L",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6560 (CuSi3Mn1) 2.1461",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuSi3",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 6560 (CuSi3Mn1) 2.1461",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuSn",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 1898A (CuSn1MnSi) 2.1006",
    Diameter: 1.2,
  },
  {
    Brandname: "ML CuSn6",
    Manufacturer: "MIGAL.CO",
    Description: "Rod/Wire electrode for Copper",
    Designation: "ISO 24373: S Cu 5180A (CuSn6P) 2.1022",
    Diameter: 1.2,
  },
  {
    Brandname: "ML 19.9 LSi",
    Manufacturer: "MIGAL.CO",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 19 9 L Si 1.4316",
    Diameter: 1.2,
  },
  {
    Brandname: "ML 23.12 LSi",
    Manufacturer: "MIGAL.CO",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 23 12 L Si 1.4332",
    Diameter: 1.2,
  },
  {
    Brandname: "ML 29.9",
    Manufacturer: "MIGAL.CO",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 29.9 1.4337",
    Diameter: 1.2,
  },
  {
    Brandname: "ML 18.8 Mn",
    Manufacturer: "MIGAL.CO",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 18 8 Mn 1.4370",
    Diameter: 1.2,
  },
  {
    Brandname: "ML 19.12.3 LSi",
    Manufacturer: "MIGAL.CO",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 19 12 3 Lsi 1.4430",
    Diameter: 1.2,
  },
  {
    Brandname: "ML 22.9.3 NL",
    Manufacturer: "MIGAL.CO",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 22 9 3 N L 1.4462",
    Diameter: 1.2,
  },
  {
    Brandname: "ML 19.12.3 NbSi",
    Manufacturer: "MIGAL.CO",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 19 12 3 NbSi 1.4576",
    Diameter: 1.2,
  },
  {
    Brandname: "ML 25.20",
    Manufacturer: "MIGAL.CO",
    Description: "Stainless steel welding wires/rods",
    Designation: "DIN EN ISO 14343-A/G: 25.20 1.4842",
    Diameter: 1.2,
  },
  {
    Brandname: "NiCr20Nb",
    Manufacturer: "MIGAL.CO",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "EN ISO 18274: S Ni 6082 (NiCr20Mn3Nb) 2.4806",
    Diameter: 1.2,
  },
  {
    Brandname: "NiCr21Mo9Nb",
    Manufacturer: "MIGAL.CO",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "EN ISO 18274: S Ni 6625 (NiCr22Mo9Nb)",
    Diameter: 1.2,
  },
  {
    Brandname: "NiCu30MnTi",
    Manufacturer: "MIGAL.CO",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "EN ISO 18274: S Ni 4060 (NiCu30Mn3Ti) 2.4377",
    Diameter: 1.2,
  },
  {
    Brandname: "NiFe2",
    Manufacturer: "MIGAL.CO",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "DIN 8573: SG - NiFe2",
    Diameter: 1.2,
  },
  {
    Brandname: "NiTi4",
    Manufacturer: "MIGAL.CO",
    Description: "Welding wires/rods for Nickel alloys",
    Designation: "DIN 1736: SG - NiTi4 2.4155",
    Diameter: 1.2,
  },
];
