export const METALS = [
  {
    GroupNumber: "1.1",
    Standard: "EN 10210-1",
    Designation: "S275NH",
    MaterialNumber: "1.0493",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.1",
    Standard: "EN 10219-1",
    Designation: "S275NLH",
    MaterialNumber: "1.0497",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.1",
    Standard: "EN 10210-1",
    Designation: "S275NLH",
    MaterialNumber: "1.0497",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.2",
    Standard: "EN 10028-6",
    Designation: "P355QL2",
    MaterialNumber: "1.8869",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.2",
    Standard: "EN 10296-1",
    Designation: "E355M",
    MaterialNumber: "1.8896",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.2",
    Standard: "EN 10208-2",
    Designation: "L360QB",
    MaterialNumber: "1.8948",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.3",
    Standard: "EN 10219-1",
    Designation: "S460NLH",
    MaterialNumber: "1.8956",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.3",
    Standard: "EN 10210-1",
    Designation: "S460NLH",
    MaterialNumber: "1.8956",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.3",
    Standard: "EN 10208-2",
    Designation: "L415NB",
    MaterialNumber: "1.8972",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.4",
    Standard: "EN 10025-5",
    Designation: "S275J2W",
    MaterialNumber: "1.8961",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.4",
    Standard: "EN 10025-5",
    Designation: "S355J2W",
    MaterialNumber: "1.8965",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "1.4",
    Standard: "EN 10025-5",
    Designation: "S355K2W",
    MaterialNumber: "1.8967",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "2.1",
    Standard: "EN 10149-2",
    Designation: "S700MC",
    MaterialNumber: "1.8974",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "2.1",
    Standard: "EN 10208-2",
    Designation: "L450MB",
    MaterialNumber: "1.8975",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "2.1",
    Standard: "EN 10149-2",
    Designation: "S650MC",
    MaterialNumber: "1.8976",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "2.2",
    Standard: "EN 10149-2",
    Designation: "S550MC",
    MaterialNumber: "1.0986",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "2.2",
    Standard: "EN 10208-2",
    Designation: "L485MB",
    MaterialNumber: "1.8977",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "2.2",
    Standard: "EN 10208-2",
    Designation: "L555MB",
    MaterialNumber: "1.8978",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "3.1",
    Standard: "EN 10025-6",
    Designation: "S550QL1",
    MaterialNumber: "1.8986",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "3.1",
    Standard: "EN 10025-6",
    Designation: "S620QL1",
    MaterialNumber: "1.8987",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "3.1",
    Standard: "EN 10025-6",
    Designation: "S690QL1",
    MaterialNumber: "1.8988",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "3.2",
    Standard: "EN 10025-6",
    Designation: "S890Q",
    MaterialNumber: "1.8940",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "3.2",
    Standard: "EN 10025-6",
    Designation: "S960Q",
    MaterialNumber: "1.8941",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "3.2",
    Standard: "EN 10025-6",
    Designation: "S890QL",
    MaterialNumber: "1.8983",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "3.3",
    Standard: "EN 10137-3",
    Designation: "S620AL",
    MaterialNumber: "1.8994",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "3.3",
    Standard: "EN 10137-3",
    Designation: "S690A",
    MaterialNumber: "1.8995",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "3.3",
    Standard: "EN 10137-3",
    Designation: "S690AL",
    MaterialNumber: "1.8996",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "4.1",
    Standard: "EN 10297-1",
    Designation: "20NiCrMo2-2",
    MaterialNumber: "1.6523",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "4.1",
    Standard: "EN 10297-1",
    Designation: "20NiCrMoS2-2",
    MaterialNumber: "1.6526",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "4.1",
    Standard: "EN 10222-2",
    Designation: "15MnCrMoNiV5-3",
    MaterialNumber: "1.6920",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "4.2",
    Standard: "EN 10216-2",
    Designation: "15NiCuMoNb5-64",
    MaterialNumber: "1.6368",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "4.2",
    Standard: "EN 10277-5",
    Designation: "34CrNiMo6",
    MaterialNumber: "1.6582",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.1",
    Standard: "EN 10085",
    Designation: "34CrAlMo5-10",
    MaterialNumber: "1.8507",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.1",
    Standard: "EN 10085",
    Designation: "41CrAlMo7-10",
    MaterialNumber: "1.8509",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.1",
    Standard: "EN 10085",
    Designation: "34CrAlNi7-10",
    MaterialNumber: "1.8550",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.2",
    Standard: "EN 10028-2",
    Designation: "11CrMo9-10",
    MaterialNumber: "1.7383",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.2",
    Standard: "EN 10085",
    Designation: "31CrMo12",
    MaterialNumber: "1.8515",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.2",
    Standard: "EN 10085",
    Designation: "24CrMo13-6",
    MaterialNumber: "1.8516",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.3",
    Standard: "EN 10216-2",
    Designation: "X11CrMo5+NT2",
    MaterialNumber: "1.7362+NT2",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.3",
    Standard: "EN 10213",
    Designation: "GX15CrMo5",
    MaterialNumber: "1.7365",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.3",
    Standard: "EN 10222-2",
    Designation: "X16CrMo5-1",
    MaterialNumber: "1.7366",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.4",
    Standard: "EN 10216-2",
    Designation: "X11CrMo9-1+L",
    MaterialNumber: "1.7386+L",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "5.4",
    Standard: "EN 10216-2",
    Designation: "X11CrMo9-1+NT",
    MaterialNumber: "1.7386+NT",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.1",
    Standard: "EN 10222-2",
    Designation: "14MoV6-3",
    MaterialNumber: "1.7715",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.1",
    Standard: "EN 10213",
    Designation: "G12MoCrV5-2",
    MaterialNumber: "1.7720",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.1",
    Standard: "EN 10083-3",
    Designation: "51CrV4",
    MaterialNumber: "1.8159",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.2",
    Standard: "EN 10085",
    Designation: "31CrMoV9",
    MaterialNumber: "1.8519",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.2",
    Standard: "EN 10085",
    Designation: "33CrMoV12-9",
    MaterialNumber: "1.8522",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.2",
    Standard: "EN 10085",
    Designation: "40CrMoV13-9",
    MaterialNumber: "1.8523",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.3",
    Standard: "EN 10216-2",
    Designation: "20CrMoV13-5-5",
    MaterialNumber: "1.7779",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.4",
    Standard: "EN 10216-2",
    Designation: "X20CrMoV11-1",
    MaterialNumber: "1.4922",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.4",
    Standard: "EN 10088-1",
    Designation: "X20CrMoV11-1",
    MaterialNumber: "1.4922",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "6.4",
    Standard: "EN 10213",
    Designation: "GX23CrMoV12-1",
    MaterialNumber: "1.4931",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "7.1",
    Standard: "EN 10088-1",
    Designation: "X10CrAlSi18",
    MaterialNumber: "1.4742",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "7.1",
    Standard: "EN 10088-1",
    Designation: "X18CrN28",
    MaterialNumber: "1.4749",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "7.1",
    Standard: "EN 10088-1",
    Designation: "X10CrAlSi25",
    MaterialNumber: "1.4762",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "7.2",
    Standard: "EN 10088-1",
    Designation: "X12CrS13",
    MaterialNumber: "1.4005",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "7.2",
    Standard: "EN 10272",
    Designation: "X12Cr13",
    MaterialNumber: "1.4006",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "7.2",
    Standard: "EN 10088-1",
    Designation: "X12Cr13",
    MaterialNumber: "1.4006",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "7.3",
    Standard: "EN 10088-1",
    Designation: "X5CrNiMoCuNb14-5",
    MaterialNumber: "1.4594",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "7.3",
    Standard: "EN 10088-1",
    Designation: "X1CrNiMoAlTi12-10-2",
    MaterialNumber: "1.4596",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "7.3",
    Standard: "EN 10088-1",
    Designation: "X5NiCrTiMoVB25-15-2",
    MaterialNumber: "1.4606",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "8.1",
    Standard: "EN 10216-5",
    Designation: "X8CrNiMoVNb16-13",
    MaterialNumber: "1.4988",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "8.1",
    Standard: "EN 10216-5",
    Designation: "X8CrNiMoVNb16-13",
    MaterialNumber: "1.4988",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "8.1",
    Standard: "EN 10216-5",
    Designation: "X10CrNiMoMnNbVB15-10-1",
    MaterialNumber: "1.4982",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "8.2",
    Standard: "EN 10088-1",
    Designation: "X8NiCrAlTi32-21",
    MaterialNumber: "1.4959",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "8.2",
    Standard: "EN 10028-7",
    Designation: "X8NiCrAlTi32-21",
    MaterialNumber: "1.4959",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "8.2",
    Standard: "EN 10088-1",
    Designation: "X12CrCoNi21-20",
    MaterialNumber: "1.4971",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "8.3",
    Standard: "EN 10088-1",
    Designation: "X12CrMnNiN18-9-5",
    MaterialNumber: "1.4373",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "8.3",
    Standard: "EN 10088-1",
    Designation: "X8CrMnNiN18-9-5",
    MaterialNumber: "1.4374",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "8.3",
    Standard: "EN 10088-1",
    Designation: "X8CrMnCuNB17-8-3",
    MaterialNumber: "1.4597",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "9.1",
    Standard: "EN 10028-4",
    Designation: "13MnNi6-3",
    MaterialNumber: "1.6217",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "9.1",
    Standard: "EN 10222-3",
    Designation: "15NiMn6",
    MaterialNumber: "1.6228",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "9.1",
    Standard: "EN 10028-4",
    Designation: "15NiMn6",
    MaterialNumber: "1.6228",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "9.2",
    Standard: "EN 10083-3",
    Designation: "30NiCrMo16-6",
    MaterialNumber: "1.6747",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "9.2",
    Standard: "EN 10083-3",
    Designation: "36NiCrMo16",
    MaterialNumber: "1.6773",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "9.2",
    Standard: "EN 10213",
    Designation: "G17NiCrMo13-6",
    MaterialNumber: "1.6781",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "9.3",
    Standard: "EN 10028-4",
    Designation: "X8Ni9",
    MaterialNumber: "1.5662",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "9.3",
    Standard: "EN 10028-4",
    Designation: "X7Ni9",
    MaterialNumber: "1.5663",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "9.3",
    Standard: "EN 10216-4",
    Designation: "X10Ni9",
    MaterialNumber: "1.5682",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "10.1",
    Standard: "EN 10028-7",
    Designation: "X2CrNiMoN22-5-3",
    MaterialNumber: "1.4462",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "10.1",
    Standard: "EN 10213",
    Designation: "GX2CrNiMoN22-5-3",
    MaterialNumber: "1.4470",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "10.1",
    Standard: "EN 10088-1",
    Designation: "X2CrNiCuN23-4",
    MaterialNumber: "1.4655",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "10.2",
    Standard: "EN 10028-7",
    Designation: "X2CrNiMoCuN25-6-3",
    MaterialNumber: "1.4507",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "10.2",
    Standard: "EN 10213",
    Designation: "GX2CrNiMoCuN25-6-3-3",
    MaterialNumber: "1.4517",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "10.2",
    Standard: "EN 10088-1",
    Designation: "X15CrNiSi25-4",
    MaterialNumber: "1.4821",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "11.1",
    Standard: "EN 10277-2",
    Designation: "C35",
    MaterialNumber: "1.0501",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "11.1",
    Standard: "EN 10250-2",
    Designation: "C35",
    MaterialNumber: "1.0501",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "11.1",
    Standard: "EN 10083-2",
    Designation: "C35",
    MaterialNumber: "1.0501",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "11.2",
    Standard: "EN 10277-2",
    Designation: "C45",
    MaterialNumber: "1.0503",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "11.2",
    Standard: "EN 10250-2",
    Designation: "C45",
    MaterialNumber: "1.0503",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "11.2",
    Standard: "EN 10083-2",
    Designation: "C45",
    MaterialNumber: "1.0503",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "11.3",
    Standard: "EN 10083-2",
    Designation: "C60E",
    MaterialNumber: "1.1221",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "11.3",
    Standard: "EN 10277-5",
    Designation: "C60R",
    MaterialNumber: "1.1223",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "11.3",
    Standard: "EN 10083-2",
    Designation: "C60R",
    MaterialNumber: "1.1223",
    MaterialName: "Steel",
  },
  {
    GroupNumber: "21",
    Standard: "EN 573",
    Designation: "EN AW-Al 99,98A",
    MaterialNumber: "EN AW-1198A",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "21",
    Standard: "EN 573",
    Designation: "EN AW-Al 99,0",
    MaterialNumber: "EN AW-1200",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "21",
    Standard: "EN 573",
    Designation: "EN AW-Al 99,5Ti",
    MaterialNumber: "EN AW-1450",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.1",
    Standard: "EN 573",
    Designation: "EN AW-Al Mn1Mg0,5",
    MaterialNumber: "EN AW-3005",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.1",
    Standard: "EN 573",
    Designation: "EN AW-Al Mn1",
    MaterialNumber: "EN AW-3103",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.1",
    Standard: "EN 573",
    Designation: "EN AW-Al Mn0,5Mg0,5",
    MaterialNumber: "EN AW-3105",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.2",
    Standard: "EN 573",
    Designation: "EN AW-Al Mg1",
    MaterialNumber: "EN AW-5005",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.2",
    Standard: "EN 573",
    Designation: "EN AW-Al Mg1,5(C)",
    MaterialNumber: "EN AW-5050",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.3",
    Standard: "EN 573",
    Designation: "EN AW-Al Mg2",
    MaterialNumber: "EN AW-5251",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.3",
    Standard: "EN 573",
    Designation: "EN AW-Al Mg3Mn",
    MaterialNumber: "EN AW-5454",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.3",
    Standard: "EN 573",
    Designation: "EN AW-Al Mg3",
    MaterialNumber: "EN AW-5754",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.4",
    Standard: "EN 573",
    Designation: "EN AW-Al Mg4Mn0,4",
    MaterialNumber: "EN AW-5186",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.4",
    Standard: "EN 573",
    Designation: "EN AW-Al Mg4,5Mn0,9",
    MaterialNumber: "EN AW-5383",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "22.4",
    Standard: "EN 573",
    Designation: "EN AW-Al Mg5Mn1",
    MaterialNumber: "EN AW-5456A",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "23",
    Standard: "EN 1706",
    Designation: "EN AC-Al Zn5Mg",
    MaterialNumber: "EN AC-71000",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "23.1",
    Standard: "EN 573",
    Designation: "EN AW-Al Si0,9MgMn",
    MaterialNumber: "EN AW-6081",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "23.1",
    Standard: "EN 573",
    Designation: "EN AW-Al Si1MgMn",
    MaterialNumber: "EN AW-6082",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "23.1",
    Standard: "EN 573",
    Designation: "EN AW-Al MgSiMn",
    MaterialNumber: "EN AW-6106",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "23.2",
    Standard: "EN 573",
    Designation: "EN AW-Al Zn6Mg0,8Zr",
    MaterialNumber: "EN AW-7003",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "23.2",
    Standard: "EN 573",
    Designation: "EN AW-Al Zn4,5Mg1",
    MaterialNumber: "EN AW-7020",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "24.1",
    Standard: "EN 1706",
    Designation: "EN AC-Al Si9",
    MaterialNumber: "EN AC-44400",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "24.1",
    Standard: "EN 573",
    Designation: "EN AC-Al Si12(Cu)",
    MaterialNumber: "EN AC-47000",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "24.1",
    Standard: "EN 1706",
    Designation: "EN AC-Al Si12(Cu)",
    MaterialNumber: "EN AC-47000",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "24.2",
    Standard: "EN 573",
    Designation: "EN AC-Al Si10Mg(Fe)",
    MaterialNumber: "EN AC-43400",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "24.2",
    Standard: "EN 1706",
    Designation: "EN AC-Al Si10Mg(Fe)",
    MaterialNumber: "EN AC-43400",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "24.2",
    Standard: "EN 573",
    Designation: "EN AC-Al Si10Mg",
    MaterialNumber: "N AC-43100",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "25.0",
    Standard: "EN 573",
    Designation: "EN AC-Al Si12Cu1(Fe)",
    MaterialNumber: "EN AC-47100",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "25.0",
    Standard: "EN 1706",
    Designation: "EN AC-Al Si12Cu1(Fe)",
    MaterialNumber: "EN AC-47100",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "25.0",
    Standard: "EN 573",
    Designation: "EN AC-Al Si12CuNiMg",
    MaterialNumber: "EN AC-48000",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "26",
    Standard: "EN 573",
    Designation: "EN AC-Al Cu4MgTi",
    MaterialNumber: "EN AC-21000",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "26",
    Standard: "EN 573",
    Designation: "EN AC-Al Cu4Ti",
    MaterialNumber: "EN AC-21100",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "26",
    Standard: "EN 1706",
    Designation: "EN AC-Al Cu4Ti",
    MaterialNumber: "EN AC-21100",
    MaterialName: "Aluminium",
  },
  {
    GroupNumber: "31",
    Standard: "EN 1652",
    Designation: "CW024A",
    MaterialNumber: "Cu-DHP",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "31",
    Standard: "EN 1653",
    Designation: "CW024A",
    MaterialNumber: "Cu-DHP",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "31",
    Standard: "EN 1652",
    Designation: "CW023A",
    MaterialNumber: "Cu-DLP",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "32.1",
    Standard: "EN 1652",
    Designation: "CW501L",
    MaterialNumber: "CuZn10",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "32.1",
    Standard: "EN 1652",
    Designation: "CW502L",
    MaterialNumber: "CuZn15",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "32.1",
    Standard: "EN 1654",
    Designation: "CW502L",
    MaterialNumber: "CuZn15",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "32.2",
    Standard: "EN 1652",
    Designation: "CW702R",
    MaterialNumber: "CuZn20Al2As",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "32.2",
    Standard: "EN 1657",
    Designation: "CW702R",
    MaterialNumber: "CuZn20Al2As",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "32.2",
    Standard: "EN 1653",
    Designation: "CW703R",
    MaterialNumber: "CuZn23Al2Co",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "33",
    Standard: "EN 1652",
    Designation: "CW454K",
    MaterialNumber: "CuSn3Zn9",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "33",
    Standard: "EN 1654",
    Designation: "CW454K",
    MaterialNumber: "CuSn3Zn9",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "33",
    Standard: "EN 1652",
    Designation: "CW450K",
    MaterialNumber: "CuSn4",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "34",
    Standard: "EN 1652",
    Designation: "CW352H",
    MaterialNumber: "CuNi10Fe1Mn",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "34",
    Standard: "EN 1655",
    Designation: "CW352H",
    MaterialNumber: "CuNi10Fe1Mn",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "34",
    Standard: "EN 1652",
    Designation: "CW350H",
    MaterialNumber: "CuNi25",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "35",
    Standard: "EN 1653",
    Designation: "CW307G",
    MaterialNumber: "CuAl10Ni5Fe4",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "35",
    Standard: "EN 1652",
    Designation: "CW303G",
    MaterialNumber: "CuAl8Fe3",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "35",
    Standard: "EN 1654",
    Designation: "CW303G",
    MaterialNumber: "CuAl8Fe3",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "36",
    Standard: "EN 1652",
    Designation: "CW401J",
    MaterialNumber: "CuNi10Zn27",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "36",
    Standard: "EN 1652",
    Designation: "CW403J",
    MaterialNumber: "CuNi12Zn24",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "36",
    Standard: "EN 1654",
    Designation: "CW403J",
    MaterialNumber: "CuNi12Zn24",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "37",
    Standard: "EN 1654",
    Designation: "CW100C",
    MaterialNumber: "CuBe1,7",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "37",
    Standard: "EN 1652",
    Designation: "CW101C",
    MaterialNumber: "CuBe2",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "37",
    Standard: "EN 1654",
    Designation: "CW101C",
    MaterialNumber: "CuBe2",
    MaterialName: "Copper",
  },
  {
    GroupNumber: "71",
    Standard: "EN 1561",
    Designation: "EN-JL1010",
    MaterialNumber: "EN-GJL-100",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "71",
    Standard: "EN 1561",
    Designation: "EN-JL1020",
    MaterialNumber: "EN-GJL-150",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "71",
    Standard: "EN 1561",
    Designation: "EN-JL1030",
    MaterialNumber: "EN-GJL-200",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "72.1",
    Standard: "EN 1563",
    Designation: "EN-JS1010",
    MaterialNumber: "EN-GJS-350-22",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "72.1",
    Standard: "EN 1563",
    Designation: "EN-JS1032",
    MaterialNumber: "EN-GJS-350-22U",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "72.1",
    Standard: "EN 1563",
    Designation: "EN-JS1030",
    MaterialNumber: "EN-GJS-400-15",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "72.2",
    Standard: "EN 1563",
    Designation: "EN-JS1015",
    MaterialNumber: "EN-GJS-350-22-LT",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "72.2",
    Standard: "EN 1563",
    Designation: "EN-JS1014",
    MaterialNumber: "EN-GJS-350-22-RT",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "72.2",
    Standard: "EN 1563",
    Designation: "EN-JS1019",
    MaterialNumber: "EN-GJS-350-22U-LT",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "73.1",
    Standard: "EN 1562",
    Designation: "EN-JM1020",
    MaterialNumber: "EN-GJMW-360-12",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "73.2",
    Standard: "EN 1562",
    Designation: "EN-JM1010",
    MaterialNumber: "EN-GJMW-350-4",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "73.2",
    Standard: "EN 1562",
    Designation: "EN-JM1030",
    MaterialNumber: "EN-GJMW-400-5",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "73.2",
    Standard: "EN 1562",
    Designation: "EN-JM1040",
    MaterialNumber: "EN-GJMW-450-7",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "73.3",
    Standard: "EN 1562",
    Designation: "EN-JM1110",
    MaterialNumber: "EN-GJMB-300-6",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "73.3",
    Standard: "EN 1562",
    Designation: "EN-JM1130",
    MaterialNumber: "EN-GJMB-350-10",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "73.3",
    Standard: "EN 1562",
    Designation: "EN-JM1140",
    MaterialNumber: "EN-GJMB-450-6",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "74",
    Standard: "EN 1564",
    Designation: "EN-JS1110",
    MaterialNumber: "EN-GJS-1000-5",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "74",
    Standard: "EN 1564",
    Designation: "EN-JS1120",
    MaterialNumber: "EN-GJS-1200-2",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "74",
    Standard: "EN 1564",
    Designation: "EN-JS1130",
    MaterialNumber: "EN-GJS-1400-1",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "76.1",
    Standard: "EN 12513",
    Designation: "EN-JN2010",
    MaterialNumber: "EN-GJN-HV350",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "76.1",
    Standard: "EN 12513",
    Designation: "EN-JN2020",
    MaterialNumber: "EN-GJN-HV520",
    MaterialName: "Cast iron",
  },
  {
    GroupNumber: "76.1",
    Standard: "EN 12513",
    Designation: "EN-JN2030",
    MaterialNumber: "EN-GJN-HV550",
    MaterialName: "Cast iron",
  },
];
