export const organizations = [
  {
    Alias: "Gimecs",
    Uri: "gimecs.com",
    CompanyName: "Gimecs GmbH",
    Location: "Berlin",
    WebSite: "http://www.gimecs.com",
  },
  {
    Alias: "MigalCo",
    Uri: "migal.co",
    CompanyName: "MIGAL.CO GmbH",
    Location: "Hamburg",
    WebSite: "http://www.migal.co",
  },
  {
    Alias: "Merkle",
    Uri: "merkle.de",
    CompanyName: "Merkle Schweissanlagen-Technik GmbH",
    Location: "Munich",
    WebSite: "https://merkle.de",
  },
  {
    Alias: "Corodur",
    Uri: "corodur.de",
    CompanyName: "Corodur Fülldraht GmbH",
    Location: "Frankfurt",
    WebSite: "www.corodur.de",
  },
  {
    Alias: "ITW Welding",
    Uri: "elgawelding.com",
    CompanyName: "ITW Welding GmbH",
    Location: "Cologne",
    WebSite: "https://elgawelding.com",
  },
  {
    Alias: "Oerlikon",
    Uri: "oerlikon.com",
    CompanyName: "OC Oerlikon Corporation AG",
    Location: "Stuttgart",
    WebSite: "https://www.oerlikon.com",
  },
  {
    Alias: "Certilas ",
    Uri: "certilas.com",
    CompanyName: "Certilas Nederland BV",
    Location: "Düsseldorf",
    WebSite: "https://certilas.com",
  },
  {
    Alias: "Tyczka",
    Uri: "tyczka-airgases.de",
    CompanyName: "Tyczka Air Gases GmbH",
    Location: "Leipzig",
    WebSite: "http://www.tyczka-airgases.de",
  },
  {
    Alias: "PanGas",
    Uri: "linde.ch",
    CompanyName: "Linde Gas Schweiz AG",
    Location: "Dresden",
    WebSite: "https://www.linde.ch",
  },
  {
    Alias: "Linde",
    Uri: "linde-gas.de",
    CompanyName: "Linde GmbH",
    Location: "Nuremberg",
    WebSite: "www.linde-gas.de",
  },
  {
    Alias: "Böhler",
    Uri: "voestalpine.com",
    CompanyName: "Voestalpine AG",
    Location: "Bremen",
    WebSite: "https://www.voestalpine.com/",
  },
];
