export const shieldingGases = [
  {
    Standard: "ISO 14175",
    Symbol: "M23",
    NominalComposition: "ArCO – 5/4",
    Brandname: "CORGON® 5S4",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 5", "O2: 4", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M25",
    NominalComposition: "ArCO – 13/4",
    Brandname: "CORGON® 13S4",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 13", "O2: 4", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M23",
    NominalComposition: "ArHeOC – 4/3,1/2",
    Brandname: "CORGON® 2S3He18",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 2", "O2: 3.1", "Ar: Balance", "He: 18.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M20",
    NominalComposition: "ArC – 10",
    Brandname: "CORGON® 10",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 10", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M20",
    NominalComposition: "ArC – 15",
    Brandname: "CORGON® 15",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 15", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M20",
    NominalComposition: "ArHeC – 30/10",
    Brandname: "CORGON® 10He30",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 10", "Ar: Balance", "He: 30.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M21",
    NominalComposition: "ArC – 18",
    Brandname: "CORGON® 18",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 18", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M21",
    NominalComposition: "ArC – 25",
    Brandname: "CORGON® 25",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 25", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArC+NO – 8/0,03",
    Brandname: "MISON® 8",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 8", "Ar: Balance", "NO: 0.03"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArC+NO – 18/0,03",
    Brandname: "MISON® 18",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 18", "Ar: Balance", "NO: 0.03"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M22",
    NominalComposition: "ArO – 8",
    Brandname: "CORGON® S8",
    Manufacturer: "Linde",
    ChemicalComposition: ["O2: 8", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M12",
    NominalComposition: "ArC – 2,5",
    Brandname: "CRONIGON® 2",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 2.5", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArC+NO – 2/0,03",
    Brandname: "MISON® 2",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 2", "Ar: Balance", "NO: 0.03"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M13",
    NominalComposition: "ArO – 1",
    Brandname: "CRONIGON® S1",
    Manufacturer: "Linde",
    ChemicalComposition: ["O2: 1", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M13",
    NominalComposition: "ArO – 3",
    Brandname: "CRONIGON® S3",
    Manufacturer: "Linde",
    ChemicalComposition: ["O2: 3", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M12",
    NominalComposition: "ArHeC – 20/2",
    Brandname: "CRONIGON® 2He20",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 2", "Ar: Balance", "He: 20.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "M12",
    NominalComposition: "ArHeC – 50/2",
    Brandname: "CRONIGON® 2He50",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 2", "Ar: Balance", "He: 50.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeHC – 30/2/0,05",
    Brandname: "CRONIGON® Ni10",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 0.05", "Ar: Balance", "He: 30.0", "H2: 2.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeC – 50/0,05",
    Brandname: "CRONIGON® Ni20",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 0.05", "Ar: Balance", "He: 50.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeNC – 5/5/0,05",
    Brandname: "CRONIGON® Ni30",
    Manufacturer: "Linde",
    ChemicalComposition: ["CO2: 0.05", "Ar: Balance", "He: 5.0", "N2: 5"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "N2",
    NominalComposition: "ArN – 2",
    Brandname: "VARIGON® N2",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "N2: 2"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "N4",
    NominalComposition: "ArNH – 2/1",
    Brandname: "VARIGON® N2H1",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "H2: 1.0", "N2: 2"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "N2",
    NominalComposition: "ArHeN – 20/2",
    Brandname: "VARIGON® N2He20",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "He: 20.0", "N2: 2"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "ArHe – 15",
    Brandname: "VARIGON® He15",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "He: 15.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "ArHe – 30",
    Brandname: "VARIGON® He30",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "He: 30.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "ArHe – 50",
    Brandname: "VARIGON® He50",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "He: 50.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "HeAr – 30",
    Brandname: "VARIGON® He70",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "He: 70.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "HeAr – 10",
    Brandname: "VARIGON® He90",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "He: 90.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "Ar+NO – 0,03",
    Brandname: "MISON® Ar",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "NO: 0.03"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArO – 0,03",
    Brandname: "VARIGON® S",
    Manufacturer: "Linde",
    ChemicalComposition: ["O2: 0.03", "Ar: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHe+NO – 30/0,03",
    Brandname: "MISON® He30",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "He: 30.0", "NO: 0.03"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeO – 15/0,03",
    Brandname: "VARIGON® He15S",
    Manufacturer: "Linde",
    ChemicalComposition: ["O2: 0.03", "Ar: Balance", "He: 15.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeO – 30/0,03",
    Brandname: "VARIGON® He30S",
    Manufacturer: "Linde",
    ChemicalComposition: ["O2: 0.03", "Ar: Balance", "He: 30.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeO – 50/0,03",
    Brandname: "VARIGON® He50S",
    Manufacturer: "Linde",
    ChemicalComposition: ["O2: 0.03", "Ar: Balance", "He: 50.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "R1",
    NominalComposition: "ArH – 2 – 15",
    Brandname: "VARIGON® H2",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "H2: 2.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "R1",
    NominalComposition: "ArH – 2 – 15",
    Brandname: "VARIGON® H15",
    Manufacturer: "Linde",
    ChemicalComposition: ["Ar: Balance", "H2: 15.0"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "N5",
    NominalComposition: "NH – 5",
    Brandname: "Formiergas 95/5",
    Manufacturer: "Linde",
    ChemicalComposition: ["H2: 5.0", "N2: Balance"],
  },
  {
    Standard: "ISO 14175",
    Symbol: "N5",
    NominalComposition: "NH – 30",
    Brandname: "Formiergas 70/30",
    Manufacturer: "Linde",
    ChemicalComposition: ["H2: 30.0", "N2: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "I1",
    NominalComposition: "Ar",
    Brandname: "Schweissargon",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: 100"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "R1",
    NominalComposition: "ArH - 2",
    Brandname: "Inoxline H2",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "H2: 2"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "R1",
    NominalComposition: "ArH - 5",
    Brandname: "Inoxline H5",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "H2: 5"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "R1",
    NominalComposition: "ArH - 7",
    Brandname: "Inoxline H7",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "H2: 7"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "R1",
    NominalComposition: "ArHeH - 3/1,5",
    Brandname: "Inoxline He3 H1",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "He: 3.0", "H2: 1.5"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "I2",
    NominalComposition: "He",
    Brandname: "Helium",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["He: 100.0"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "ArHe - 15",
    Brandname: "Aluline He 15",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "He: 15.0"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "ArHe - 30",
    Brandname: "Aluline He 30",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "He: 30.0"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "ArHe - 50",
    Brandname: "Aluline He 50",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "He: 50.0"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "HeAr - 30",
    Brandname: "Aluline He 70",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "He: 70.0"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "I3",
    NominalComposition: "HeAr - 10",
    Brandname: "Aluline He 90",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "He: 90.0"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "I1",
    NominalComposition: "Ar",
    Brandname: "Schweissargon spezial",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: 100"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "N2",
    NominalComposition: "ArN - 2,5",
    Brandname: "Inoxline N2",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "N2: 2.5"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeN - 15/0,015",
    Brandname: "Aluline He 15 N",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "He: 15.0", "N2: 0.015"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeN - 30/0,015",
    Brandname: "Aluline He 30 N",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "He: 30.0", "N2: 0.015"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeN - 50/0,015",
    Brandname: "Aluline He 50 N",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "He: 50.0", "N2: 0.015"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArN - 0,015",
    Brandname: "Aluline N",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["Ar: Balance", "N2: 0.015"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M20",
    NominalComposition: "ArC - 8",
    Brandname: "Ferroline C8",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 8", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M21",
    NominalComposition: "ArC - 18",
    Brandname: "Ferroline C18",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 18", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M21",
    NominalComposition: "ArC - 25",
    Brandname: "Ferroline C25",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 25", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M22",
    NominalComposition: "ArO - 4",
    Brandname: "Ferroline X4",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["O2: 4.0", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M22",
    NominalComposition: "ArO - 8",
    Brandname: "Ferrolien X8",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["O2: 8.0", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M24",
    NominalComposition: "ArCO - 6/1",
    Brandname: "Ferroline C6 X1",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 6", "O2: 1.0", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M24",
    NominalComposition: "ArCO - 12/2",
    Brandname: "Ferroline C12 X2",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 12", "O2: 2.0", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M23",
    NominalComposition: "ArCO - 5/5",
    Brandname: "Ferroline C5 X5",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 5", "O2: 5.0", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M20",
    NominalComposition: "ArHeC -20/8",
    Brandname: "Ferroline He 20 C8",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 8", "Ar: Balance", "He: 20.0"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "C1",
    NominalComposition: "C",
    Brandname: "Kohlendioxid",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 100"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M13",
    NominalComposition: "ArO - 2",
    Brandname: "Inoxline X2",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["O2: 2.0", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M12",
    NominalComposition: "ArC - 2",
    Brandname: "Inoxline C2",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 2", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "Z",
    NominalComposition: "ArHeHC - 30/2/0,12",
    Brandname: "Inoxline He30 H2 C",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 0.12", "Ar: Balance", "He: 30.0", "H2: 2"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M12",
    NominalComposition: "ArHeC - 15/2",
    Brandname: "Inoxline He15 C2",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 2", "Ar: Balance", "He: 15.0"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "M14",
    NominalComposition: "ArCO - 3/1",
    Brandname: "Inoxline C3 X1",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["CO2: 3", "O2: 1.0", "Ar: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "N5",
    NominalComposition: "NH -2",
    Brandname: "Formiergas H2",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["H2: 2", "N2: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "N5",
    NominalComposition: "NH -5",
    Brandname: "Formiergas H5",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["H2: 5", "N2: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "N5",
    NominalComposition: "NH -8",
    Brandname: "Formiergas H8",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["H2: 8", "N2: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "N5",
    NominalComposition: "NH -10",
    Brandname: "Formiergas H10",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["H2: 10", "N2: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "N5",
    NominalComposition: "NH -12",
    Brandname: "Formiergas H12",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["H2: 12", "N2: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "N5",
    NominalComposition: "NH -15",
    Brandname: "Formiergas H15",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["H2: 15", "N2: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "N5",
    NominalComposition: "NH -20",
    Brandname: "Formiergas H20",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["H2: 20", "N2: Balance"],
  },
  {
    Reference: "ISO 14175",
    Symbol: "N1",
    NominalComposition: "N",
    Brandname: "0Stickstoff",
    Manufacturer: "Messer Group",
    ChemicalComposition: ["N2: 100"],
  },
];
